name: Rust

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  load-dynamic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy (load-dynamic)
      run: cargo clippy --no-default-features --features ts-rust,load-dynamic -- -D warnings
    - name: Build (load-dynamic)
      run: cargo build --no-default-features --features ts-rust,load-dynamic --verbose
    - name: Run tests (load-dynamic)
      run: cargo test --no-default-features --features ts-rust,load-dynamic --verbose
